- flake8_typing_only_imports/__init__.py
- flake8_typing_only_imports/checker.py
- pyproject.toml
- tests/test_tyo200.py
> Improve type checking block discovery

- README.md
- flake8_type_checking/checker.py
- flake8_type_checking/codes.py
- tests/test_tc005.py
> Add check for empty type checking block

- .github/workflows/testing.yml
- flake8_type_checking/checker.py
- poetry.lock
- setup.cfg
Need to resolve some Python 3.8 tests before merging.
> Revise test workflow

- README.md
- flake8_type_checking/checker.py
- flake8_type_checking/plugin.py
- pyproject.toml
- setup.cfg
- tests/__init__.py
- tests/test_exempt_modules.py
> Add setting for ignoring TC001/TC002 errors from certain imports/modules

- README.md
- flake8_type_checking/checker.py
- flake8_type_checking/plugin.py
- pyproject.toml
- tests/__init__.py
- tests/test_errors.py
- tests/test_import_visitors.py
- tests/test_name_visitor.py
- tests/test_pydantic.py
> Add Pydantic support

- .github/workflows/testing.yml
- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
- tests/test_tc200.py
Running plain coverage is plenty.
> chore: Remove pytest-cov

- .pre-commit-config.yaml
- flake8_type_checking/checker.py
- Ignore private properties
- Make plugin custom property private
Hopefully fixes #74
> Ignore private ast-node properties

- .github/workflows/testing.yml
- .pre-commit-config.yaml
- flake8_type_checking/checker.py
- flake8_type_checking/plugin.py
- poetry.lock
- pyproject.toml
- tests/__init__.py
- tests/conftest.py
- tests/test_errors.py
- tests/test_should_warn.py
Remove internal code for classifying imports in favour of a dependency.
> Replace import classification

- flake8_type_checking/checker.py
- flake8_type_checking/constants.py
- flake8_type_checking/types.py
- tests/__init__.py
Simplifies the code a little (to my eyes at least).
> refactor: (c)attrs support 

- flake8_type_checking/checker.py
- pyproject.toml
> fix: Replace NodeTransformer with NodeVisitor

- flake8_type_checking/checker.py
Removes hacky base classes for mixins. This seemed like an acceptable way to get proper type hinting for methods not present in the mixin, but on the NodeVisitor class; but it can actually cause problems in overload logic among other things.
> Improve typing

- flake8_type_checking/checker.py
- tests/test_errors.py
> Handle double-namespace imports

- flake8_type_checking/plugin.py
- tests/conftest.py
I'm not exactly sure if this is the best way to fix this issue, but this seems to be the only way to fix without haven't to rewrite a whole lot of tests.
> Fix #96 none handling for select and extend-select

- .github/workflows/testing.yml
- README.md
- flake8_type_checking/constants.py
- flake8_type_checking/plugin.py
- poetry.lock
- pyproject.toml
> chore: Add different flake8 versions to test workflow

- flake8_type_checking/checker.py
- tests/test_errors.py
> Fix TC004 false positives

- flake8_type_checking/checker.py
- tests/test_errors.py
- tests/test_exempt_modules.py
- tests/test_tc001_to_tc003.py
> Stop flagging unused imports

- .github/workflows/testing.yml
- poetry.lock
In part doing this to test https://github.com/snok/install-poetry/pull/90
> chore: Update Poetry version to 1.2.0

- flake8_type_checking/plugin.py
- tests/conftest.py
> fix: Ignore TC100 for stub files

- flake8_type_checking/plugin.py
- tests/test_should_warn.py
idk if you want something in the readme as well, but otherwise a very simple implementation.
fixes #152
> disable the plugin entirely for stub files

- flake8_type_checking/checker.py
- tests/test_exempt_modules.py
> Added the ability to skip a module by template

- flake8_type_checking/checker.py
- tests/test_errors.py
Fixes https://github.com/snok/flake8-type-checking/issues/156
> Add support for `if TYPE_CHECKING is True` operation

- flake8_type_checking/checker.py
- tests/test_tc200.py
> fix: Annotations inside `if TYPE_CHECKING:` should not result in TC200

- flake8_type_checking/checker.py
- tests/test_tc201.py
> fix: Wrapped annotations with subscripted types should not raise TC201

- flake8_type_checking/checker.py
- tests/test_tc001_to_tc003.py
- tests/test_tc004.py
> feat: Add support for `singledispatch`/`singledispatchmethod`
