snok/flake8-type-checking

flake8_typing_only_imports/checker.py
tests/test_name_visitor.py
tests/test_tyo100.py
tests/test_tyo101.py

Code like this
```python
import proj.app.enums
class Migration:
enum=proj.app.enums.EnumClass
```
which is just a simplified example of a Django migration file, was flagging false positives.
The problem is that the current code does not register that `proj.app.enums.EnumClass` is related to the `proj.app.enums` import in any way. 
I'm not super excited about this way of solving the problem, but this fixes the test example without breaking the existing test suite. Any feedback here, on how it might be cleaned up is much appreciated @JonasKs

Register nested attributes

---

.pre-commit-config.yaml
flake8_type_checking/checker.py
flake8_type_checking/constants.py
poetry.lock
pyproject.toml
tests/__init__.py
tests/test_errors.py

This seems like the missing piece of the puzzle. 
Not convinced this check is anywhere near robust enough to be used yet, but if we could make this work, that should close the loop on type-checking import management.

Add TCH004 to warn about used type checking imports

---

flake8_type_checking/checker.py
tests/test_errors.py
tests/test_tc004.py

Turns out we hadn't yet handled `*args` and `**kwargs` style type annotations, which lead to false `TC004` positives

Resolve failing TC004 test

---

flake8_type_checking/checker.py
poetry.lock
pyproject.toml
tests/test_tc002.py

This code was not generating any warnings
```python
from typing import Any, Generator, Union
if TYPE_CHECKING:
ImportType = Union[ast.Import, ast.ImportFrom]
Flake8Generator = Generator[tuple[int, int, str, Any], None, None]
```
With some small changes it now correctly tells users to move all typing imports into the type checking block.

Prevent use mapping from inside type-checking blocks

---

tests/test_should_warn.py

Currently, the unit tests fail under Windows. When using os.sep instead of hard coded "/", the unit tests can be platform independent.

Use os.sep instead of "/" in order to make tests platform independent

---

README.md
flake8_type_checking/codes.py
tests/test_errors.py
tests/test_should_warn.py

Remove colon after codes in order to comply with "--format=%(code)s"

---

flake8_type_checking/checker.py
tests/test_tc005.py

TC005 is meant to catch residual empty type-checking blocks like this:
```python
if TYPE_CHECKING:
pass
```
Right now the logic only checks for imports within a type-checking block and raises a TC005 if no imports are found. This is not quite right, since type-checking blocks are often used, e.g., within class scopes to override local types.
This PR changes the logic so it's even simpler. Now we only flag an error if the type-checking block only contains a pass statement.

TC005 logic fix

---

.pre-commit-config.yaml
flake8_type_checking/checker.py
flake8_type_checking/plugin.py
flake8_type_checking/types.py
poetry.lock
setup.cfg
tests/__init__.py
tests/test_import_visitors.py

Enable mypy strict mode and fix relevant errors.
Among other things, this forced us to split the `function_scopes` dict
into two parts - but this seems like an improvement.

Improve type checking

---

flake8_type_checking/checker.py
tests/test_name_visitor.py
tests/test_tc004.py

Solves https://github.com/snok/flake8-type-checking/issues/55
The implementation in https://github.com/snok/flake8-type-checking/pull/11 / #7 mistakenly added all string constants to our uses mapping.

Correct handling of __all__ declarations

---

flake8_type_checking/checker.py
tests/test_errors.py

The __all__ declaration fix from #7 only worked for single line declarations. This adds support for multi-line declarations.

Fix __all__ assignment end_lineno inference

---

flake8_type_checking/checker.py
flake8_type_checking/plugin.py
pyproject.toml
tests/__init__.py
tests/test_errors.py
tests/test_fastapi_decorators.py
tests/test_import_visitors.py
tests/test_name_visitor.py

Record decorated function argument and keyword argument
annotations as uses, to prevent flagging these as TC001
and TC002 errors. These are evaluated at runtime by FastAPI
This only handles decorated functions, meaning any annotation in 
a dependency function (any function passed to `Depends`) is still at risk 
of being flagged as a candidate for guarding, while being evaluated at runtime.
Re discussion in #52, I'm not 100% sure what design makes the most sense. Might
make FastAPI support include handling of just decorators and create a separate function
for dependencies (or vice versa).

feat: Add partial FastAPI support

---

flake8_type_checking/plugin.py

I'm not sure exactly what triggered this (it doesn't always happen even when `enable_extensions` is unset), but I got the following traceback:
```pytb
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
File "/home/nyuszika7h/.pyenv/versions/3.10.1/lib/python3.10/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/home/nyuszika7h/.pyenv/versions/3.10.1/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
return list(map(*args))
File ".venv/lib/python3.10/site-packages/flake8/checker.py", line 621, in _run_checks
return checker.run_checks()
File ".venv/lib/python3.10/site-packages/flake8/checker.py", line 531, in run_checks
self.run_ast_checks()
File ".venv/lib/python3.10/site-packages/flake8/checker.py", line 435, in …
```

Fix error when `enable_extensions` is not set

---

.pre-commit-config.yaml
flake8_type_checking/checker.py
setup.cfg
tests/test_attrs.py

- implemented a method that compiles imports in regard to `attrs` including their import alias
- check at class definitions if any decorator is one of `attrs` dataclass decorators (matched against the actual import alias)

Proposal to implement `attrs` support

---

.github/workflows/testing.yml
.pre-commit-config.yaml
README.md
flake8_type_checking/checker.py
flake8_type_checking/plugin.py
pyproject.toml
tests/test_errors.py
tests/test_import_visitors.py
tests/test_name_visitor.py

Makes the attrs logic added for v1.4.0 opt-in, using the `cattrs-enabled` setting.
For complete `cattrs` support we should also add dataclass detection, but I'm happy with leaving it partially implemented for now. Seems more important to fix unnecessarily ignoring attrs definitions for now.

Add cattrs settings

---

.github/workflows/testing.yml
flake8_type_checking/plugin.py

We do modify the tree quite a bit in the
checker, and that seems to lead to issues,
as documented in #71. This fixes the
example documented in the issue.

fix: Pass copied tree to checker class

---

.github/workflows/testing.yml
.pre-commit-config.yaml
flake8_type_checking/checker.py
flake8_type_checking/plugin.py
flake8_type_checking/types.py
poetry.lock
setup.cfg
tests/test_attrs.py
tests/test_errors.py

PR implements the change in behaviour suggested in #84. Where we have previously flagged unused imports, we will now flag unused imports only if there are no other used imports from the same module.

Flag imports on a per-module basis

---

flake8_type_checking/plugin.py

~Running flake8-type-checking on a larger work project, I'm seeing recursion limit errors in the ast-tree copying. It's not an infinite recursion issue, as increasing the limit to 3-4000 seems to resolve it. From what I can tell, increasing the recursion limit can lead to segfaults if the recursion limit exceeds the system limit, but that 10,000 should be very conservative.~
~We added the copying because of #71, and ideally it would be nice to keep that in, so this seems like the best option. At the same time, I'm open to input/suggestions for how to resolve this in a better way. Tinkering with sys settings seems a little out of scope for a linter plugin.~
After trying to reproduce #71 in the latest Pytest release + [b3f22c4](https://github.com/snok/flake8-type-checking/pull/89/commits/b3f …

fix: Add recursion limit override for copy

---

README.md

Judging from what's in the 2.0.0 release notes here, TC002 is for third-party, and TC003 is for built-in, so this updates the README to reflect that.

Fix error code in README

---

flake8_type_checking/checker.py
tests/test_tc004.py

Annotations in positional-only args were not being handled, which resulted in contained names being interpreted as runtime usages:
```py
from __future__ import annotations
from typing import TYPE_CHECKING
if TYPE_CHECKING:
from typing import List
def func(data: List[int], /) -> None:
...
```
```sh
$ flake8 --select TC004 test.py
test.py:6:1: TC004 Move import 'List' out of type-checking block. Import is used for more than type hinting.
```
Hope I put the test in the correct place, let me know if it's better suited for another file 😅

fix: handle annotations in positional-only args

---

flake8_type_checking/checker.py
tests/test_pydantic.py

PR adds support for the `validate_arguments`-decorator. When Pydantic support is enabled, this should make it so function arguments are treated as needed-at-runtime when the decorator is found.
Solves #97

Add support for Pydantic's `@validate_arguments`

---

flake8_type_checking/checker.py
flake8_type_checking/constants.py

PR changes the plugin behaviour from deleting annotations on node objects, to annotating them with a private property that we later use to ignore annotations in `visit_Name`.
Solves #95

feat: Replace annotation deletion with attribute write

---

.github/workflows/testing.yml
flake8_type_checking/constants.py
poetry.lock
pyproject.toml

PR removes packaging in favour of a tuple comparison. We need to know whether the installed flake8 version is 4 or above, and this should hopefully do the trick without requiring any external dependencies.
The PR also adds a `flake8` call in the test workflow, so we can discover these types of issues before a new version is released in the future.
Solves #111

Remove `packaging` dependency

---

flake8_type_checking/checker.py
poetry.lock
pyproject.toml

The package was rewritten and renamed when v4 was released.

Replace `aspy.refactor-imports` with `classify-imports`.

---

README.md
flake8_type_checking/checker.py
flake8_type_checking/constants.py
poetry.lock
pyproject.toml
tests/test_tc006.py

Add `TC006` rule for string literal types in `typing.cast()`

---

flake8_type_checking/checker.py
tests/test_tc101.py

This PR changes the code related to the TC101 check to only show errors if there's a `str` literal/constant, not any other type.
There are valid use-cases for literals that don't represent types in annotation subscripts, especially with the introduction of `typing.Annotated`, like `x: Annotated[int, 42]` or generally custom types with `__class_getitem__`.
Adding on to this, I suppose `Annotated[int, "stuff"]` should technically also be allowed, but it's not possible to generally differentiate between contexts where a string literal is meant to represent a type (e.g. `Dict[str, "int"]`), and where it doesn't (e.g. `Annotated[str, "int"]`), without hardcoding specific generic types.
As such, this is by far not a perfect solution, but it should get a bit closer :)
For context, this first …

fix: only raise TC101 for `str` literals

---

flake8_type_checking/constants.py
tests/test_attrs.py

The `attrs` package has two additional decorators that are aliases for `@attrs.define` which should be included:
- `attrs.mutable()` is an alias for `attrs.define()`
- `attrs.frozen()` is an alias for `define(frozen=True)`
See https://www.attrs.org/en/stable/names.html#tl-dr

feat: Support `@attrs.frozen` and `@attrs.mutable`

---

poetry.lock
pyproject.toml

I've removed the upper bound of the Python version specifier in `pyproject.toml`, i.e. I've replaced the version specifier `^` by `>=`.
Capping the Python version (e.g. `<4`) is a bad practice.
* https://github.com/pypa/packaging.python.org/pull/850
* https://iscinumpy.dev/post/bound-version-constraints/#pinning-the-python-version-is-special
* https://discuss.python.org/t/requires-python-upper-limits/12663

chore: remove upper bound from Python version specifier

---

README.md
flake8_type_checking/checker.py
flake8_type_checking/plugin.py
pyproject.toml
tests/conftest.py
tests/test_strict.py

feat: Add strict setting to opt-into v1 behavior

---

flake8_type_checking/checker.py

In 54dde2e59955318937a3d21f88b34deb9bc74a4f a fix was implemented for "double namespace" imports, where a module is imported like
```python
import urllib.parse
```
and then referenced like
```python
urllib.parse.urlencode(some_string)
```
The issue causing this behavior was actually the handling of "nested" attributes originally added in 77f9c3a2712592fd12fe10e6bfa00c8a4b89b9a6, and since removed e4362ecc0c66ed16ca541f386d4b651800240959. By performing the removal in e4362ecc0c66ed16ca541f386d4b651800240959, the test suite passes without the "double namespace" fix.
Removing this code also removes two lines that would never actually be called when running the code, and therefore could not have any test coverage.

Remove fix for "double namespace" imports

---

tests/conftest.py
tests/test_tc100.py

This adds some simple test coverage for 7d32365bf5091837bbc4247e1d5fbc2d5e438d9e.

Add test coverage for stub file ignore

---

flake8_type_checking/checker.py
tests/test_errors.py

For various reasons, modules may be conditioned on multiple criteria that determine whether they should be imported. For example, if we have an module that should be imported during testing or type checking, we may do something like:
```python
if TYPE_CHECKING or environment == 'test':
import foobar
```
Currently, the linter will flag the `foobar` import as needing to be moved into an `if TYPE_CHECKING` block in this scenario. This gives us two options, each of which is less than ideal. We could import the module twice, i.e.
```python
if TYPE_CHECKING:
import foobar
elif environment == 'test':
import foobar
```
or use a `# noqa` comment and lose the safety of the check when the code changes.
This commit adds some logic to handle these types of simple conditionals and determine if they are …

feat: Support use of TYPE_CHECKING with simple boolean logic

---

flake8_type_checking/checker.py

It is not necessary to create a `set`, we just need one valid case.

Make `is_exempt_module` work with an iterator

---

flake8_type_checking/checker.py
flake8_type_checking/types.py
tests/test_errors.py
tests/test_tc004.py

Closes #160 
Prevents false positive TC004 errors when an import name is shadowed by function arguments.

Add failing test

---

flake8_type_checking/checker.py
tests/test_tc201.py

I found another false positive for TC201 when a wrapped annotation is more complex than directly referring to a defined class name.
I changed the condition for `class_name` to match the one for `import_name`. This should be more consistent.

fix: TC201 should never emit for classes defined in-file

---

flake8_type_checking/checker.py
flake8_type_checking/constants.py
tests/test_name_extraction.py
tests/test_tc201.py

Things are looking really good now with v2.5.0, I only had to add about two or three `noqa` comments on a medium sized project, compared to the hundreds I would've had to add before, nevertheless the `noqa` I had to add were TC201 errors that would cause a runtime exception, so I think it's better we treat this like subscripts.
Specifically the following is one such case:
```python
from lxml import etree
element: 'etree._Element'   # TC201
```
`_Element` only exists in the stubs, so unwrapping that annotation would result in a runtime error.
I've adjusted the RegEx for name extraction to only include the LHS on attribute access, this matches what `add_annotation` does, although I'm not quite sure what it's doing right now is correct, since for `uses` we also record `lhs.rhs`, presumably …

fix: Avoid potentially harmful TC201 false positives

---

README.md
flake8_type_checking/checker.py
flake8_type_checking/constants.py
flake8_type_checking/types.py
setup.cfg
tests/conftest.py
tests/test_tc004.py
tests/test_tc008.py
tests/test_tc009.py
tests/test_tc100.py
tests/test_tc101.py
tests/test_tc200.py
tests/test_tc201.py

Extends TC100/TC200 to deal with type checking declarations
Avoids a couple of false positives in TC100/TC101
Avoids contradicting TC004/TC009 errors vs. TC100/TC200 errors
Closes #131
Closes #172 
This passes some of the fixes I've already applied to TC200/TC201 along to TC100/TC101 but also improves handling of type checking declarations for TC100/TC200.
In order to avoid introducing false positives/misleading errors I've also added TC009 to be the equivalent of TC004 for type checking declarations.

Adds TC009 for type checking declarations used at runtime

---

README.md
flake8_type_checking/checker.py
flake8_type_checking/constants.py
flake8_type_checking/plugin.py
setup.cfg
tests/conftest.py
tests/test_import_visitors.py
tests/test_name_visitor.py
tests/test_sqlalchemy.py

Adds support for SQLAlchemy 2.0 `Mapped` annotations

---

README.md
flake8_type_checking/checker.py
flake8_type_checking/constants.py
tests/test_tc008.py
tests/test_tc010.py
tests/test_tc201.py

feat: Add TC010 which detects invalid use of string literals with |

---

flake8_type_checking/checker.py
tests/test_tc200.py

feat: Add support for PEP646 syntax for unpacking `TypeVarTuple`

---

flake8_type_checking/checker.py
tests/test_tc100.py
tests/test_tc101.py
tests/test_tc200.py
tests/test_tc201.py

fix: ann assignments inside function bodies should never be quoted

---

flake8_type_checking/checker.py
flake8_type_checking/constants.py
tests/test_name_extraction.py
tests/test_tc001_to_tc003.py

This is a partial fix for #192
This is probably not a huge change, since we skipped unexpected nodes within annotations already, so it would mostly get rid of some false positives where a string within `Annotated` happened to match one of the imported symbols and thus being treated as a forward reference incorrectly.
I still need to think about a solution for string annotations and whether or not we should visit the nodes we're currently skipping, maybe we should pass `self` into `AnnotationVisitor` so we can call the `generic_visit` of the outer visitor?

fix: `typing.Annotated` should be special-cased like `typing.Literal`

---

flake8_type_checking/checker.py
flake8_type_checking/plugin.py
tests/conftest.py
tests/test_import_visitors.py
tests/test_sqlalchemy.py
tests/test_tc001_to_tc003.py
tests/test_tc006.py

This should make some checks a lot more robust and makes it easier to add similarly robust checks to library specific mixins.
This is also a precursor to using `is_typing` in the annotation visitor, so we can handle aliases and module level accesses of `Literal` and `Annotated`.

refactor: Create a common utility for looking up fully qualified names

---

flake8_type_checking/checker.py
flake8_type_checking/types.py
tests/test_name_extraction.py
tests/test_name_visitor.py
tests/test_sqlalchemy.py
tests/test_tc001_to_tc003.py

Makes soft use concept of `mapped_names` more generic and reuse it for walking `Annotated` value expressions.
Closes: #192

refactor: Make use of `is_typing` for `Literal`/`Annotated` detection.

---

flake8_type_checking/checker.py
tests/test_fastapi_decorators.py

Closes #185 
Also fixes the same bug for Pydantic and singledispatch

fix: Make sure to visit `returns` not just the argument annotations

---

README.md
flake8_type_checking/checker.py
flake8_type_checking/plugin.py
tests/conftest.py
tests/test_force_future_annotation.py

feat: Add new setting to enforce future imports for all annotations

---

flake8_type_checking/checker.py
flake8_type_checking/constants.py
flake8_type_checking/types.py

Gets rid of some complex code we no longer need, since `lookup_full_name` already gives us what we want.

refactor: Simplifies attrs support
